FROM ruby:3.3.5

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN gem install bundler && bundle install

COPY . .

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
