default: &default
  adapter: postgresql
  encoding: unicode
  pool: 16

development:
  <<: *default
  database: blog_development
  username: "postgres" # Matches POSTGRES_USER
  password: "postgres" # Matches POSTGRES_PASSWORD
  host: "db" # 'db' refers to the db service in docker-compose.yml
  port: "5432"

test:
  <<: *default
  database: blog_test
  username: "postgres"
  password: "postgres"
  host: "db"
  port: "5432"
