default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development
  username: "postgres" # Matches POSTGRES_USER
  password: "postgres" # Matches POSTGRES_PASSWORD
  host: "db" # 'db' refers to the db service in docker-compose.yml
  port: "5432"

test:
  <<: *default
  database: blog_test
  username: "postgres"
  password: "postgres"
  host: "db"
  port: "5432"

production:
  primary: &primary_production
    <<: *default
    database: blog_production
    username: blog
    password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: blog_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: blog_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: blog_production_cable
    migrations_paths: db/cable_migrate
